exclude mips linux because of byteswap.h
[ERROR]    /Users/runner/work/crosstool-ng/crosstool-ng/.build/src/linux-5.8.9/arch/mips/tools/elf-entry.c:2:10: fatal error: 'byteswap.h' file not found
[ALL  ]    #include <byteswap.h>
[ALL  ]             ^~~~~~~~~~~~

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>